# Generated by Django 4.1.5 on 2023-01-23 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creditaidjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
