# Generated by Django 4.1.5 on 2023-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditaidjango', '0003_predictor_ktppicture_predictor_selfiepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='ktppicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/ktp/'),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='selfiepicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/selfie/'),
        ),
    ]
