# Generated by Django 4.1.5 on 2023-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditaidjango', '0005_alter_predictor_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='ktppicture',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='selfiepicture',
        ),
        migrations.AddField(
            model_name='predictor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
